import { ToolDefinition } from '@/types/tools';

export const tools: ToolDefinition[] = [
  {
    id: 'pdf-to-image',
    name: 'PDF to Image',
    description: 'PDF를 JPG/PNG 이미지로 변환하고, NotebookLM 워터마크를 제거합니다.',
    icon: 'FileImage',
    href: '/tools/pdf-to-image',
    category: 'PDF',
    isNew: false,
  },
  {
    id: 'image-to-pdf',
    name: 'Image to PDF',
    description: 'JPG, PNG, GIF 이미지를 하나의 PDF 파일로 합칩니다. 순서 변경 가능.',
    icon: 'FileUp',
    href: '/tools/image-to-pdf',
    category: 'PDF',
    isNew: false,
  },
  {
    id: 'video-scene-detect',
    name: 'Video Scene Detect',
    description: '동영상에서 장면이 바뀌는 시점을 자동으로 감지합니다.',
    icon: 'ScanSearch',
    href: '/tools/video-scene-detect',
    category: 'Video',
    isNew: false,
  },
  {
    id: 'bg-remove',
    name: '배경 제거',
    description: '이미지 배경을 투명하게 만듭니다. 색상 선택 후 원클릭 제거.',
    icon: 'Eraser',
    href: '/tools/bg-remove',
    category: 'Image',
    isNew: false,
  },
  {
    id: 'image-resize',
    name: '이미지 리사이즈',
    description: '이미지 크기를 변경합니다. 비율 잠금, 포맷 변환 지원.',
    icon: 'Scaling',
    href: '/tools/image-resize',
    category: 'Image',
    isNew: false,
  },
  {
    id: 'qr-generator',
    name: 'QR코드 생성기',
    description: '텍스트나 URL을 QR코드 이미지로 변환합니다.',
    icon: 'QrCode',
    href: '/tools/qr-generator',
    category: 'Utility',
    isNew: false,
  },
  {
    id: 'pdf-annotate',
    name: 'PDF 강의 도구',
    description: 'PDF 위에 그림, 메모, 형광펜을 추가하고 저장합니다.',
    icon: 'PenTool',
    href: '/tools/pdf-annotate',
    category: 'PDF',
    isNew: false,
  },
  {
    id: 'image-edit',
    name: '이미지 편집기',
    description: '밝기, 대비, 채도 조정과 인스타 스타일 필터, 크롭 기능.',
    icon: 'ImageIcon',
    href: '/tools/image-edit',
    category: 'Image',
    isNew: true,
  },
];

export const siteConfig = {
  name: 'Flux Utility',
  description: '빠르고 간편한 온라인 유틸리티 모음',
  url: 'https://flux-utility.vercel.app',
};
